### ISSUE TITLE
twitter publish link key fails: case sensitive

### ISSUE THREAD

**Issue by bvdlingen** [keys-pub/keys#30]
I noticed the following:

When generating a key for twitter the username must be lowercase, this is enforced on the linux client: `name should be lowercase.`
 So I entered my twitter username in lowercase and continued. However publishing the key works, validation fails because my username contains some letters in uppercase
`failed to create user: path invalid (name mismatch)`

**Comment by gabriel** [comment]
Thanks for the bug report, this is a known issue, should have a fix out today. Does it resolve if you lowercase the name in the link to the tweet?

**Comment by Fastidious** [comment]
@gabriel, piggy backing here, as the same occurs with Reddit.

**Comment by gabriel** [comment]
Fixed in v0.0.43 via https://github.com/keys-pub/keys/pull/25.

**Comment by Deozaan** [comment]
@gabriel I still can't verify with Reddit using v0.0.43 due to this bug.

My username is capitalized. No matter how I enter it (lowercase or capitalized) when I use the Windows client, it fails.

**Comment by gabriel** [comment]
Found another issue with reddit username characters.. fix in progress. Thanks for reporting the issue.

**Comment by gabriel** [comment]
Fix should be in v0.0.45, just released.

**Comment by Deozaan** [comment]
Thank you. I can confirm it works now. 👍
